e_com_foundation/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('listing_app.urls')),
    path('admin/', admin.site.urls),
]

listing/urls.py
from django.urls import path

from . import views

from django.http import HttpResponse
def cart(request, id):
    return HttpResponse(f"This is the cart of {id}")

name = 'listing'
urlpatterns = [
    path('',views.index),
    path('listings',views.ListingListView.as_view(), name="listing-list"),
    path('products',views.ProductListView.as_view(), name="product-list"),
    path('services',views.ServiceListView.as_view(), name="service-list"),
    path('listing/<slug:slug>',views.ListingDetailView.as_view(), name="listing-detail"),
    path('product/<slug:slug>',views.ProductDetailView.as_view(), name="product-detail"),
    path('service/<slug:slug>',views.ServiceDetailView.as_view(), name="service-detail"),
    path('cart/<int:id>/', cart, name="add-to-cart")
]

listing_app/urls.py
from django.urls import path

from . import views

from django.http import HttpResponse
def cart(request, id):
    return HttpResponse(f"This is the cart of {id}")

name = 'listing_app'
urlpatterns = [
    path('',views.index),
    path('listings',views.ListingListView.as_view(), name="listing-list"),
    path('products',views.ProductListView.as_view(), name="product-list"),
    path('services',views.ServiceListView.as_view(), name="service-list"),
    path('listing/<slug:slug>',views.ListingDetailView.as_view(), name="listing-detail"),
    path('product/<slug:slug>',views.ProductDetailView.as_view(), name="product-detail"),
    path('service/<slug:slug>',views.ServiceDetailView.as_view(), name="service-detail"),
    path('cart/<int:id>/', cart, name="add-to-cart")
]

order_app/urls.py
from django.urls import path

from . import views

name = 'order_app'
urlpatterns = [
    path('cart',views.cart)
]

listing_app/models.py
from django.db import models
from django.utils import timezone
from django.utils.html import format_html
from django.utils.text import slugify

class Price(models.Model):
    mrp = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    saleprice = models.DecimalField(max_digits=10, decimal_places=2)
    offerprice = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    currency = models.ForeignKey('Currency', on_delete=models.CASCADE)
    listing = models.ForeignKey('Listing', on_delete=models.CASCADE)
    unit = models.ForeignKey('Unit', on_delete=models.CASCADE)

    def __str__(self):
        return f'Price: {self.saleprice} {self.currency.code} per {self.unit.symbol}'

class Media(models.Model):
    MEDIA_TYPES = (
        ('Image', 'Image'),
        ('Video', 'Video'),
    )
    media_type = models.CharField(max_length=5, choices=MEDIA_TYPES)
    file = models.FileField(upload_to='media/')
    listing = models.ForeignKey('Listing', on_delete=models.CASCADE)
    
    def __str__(self):
        return f'Media: {self.media_type}'
    
    def preview(self):
        if self.media_type == 'Video':
            return format_html('<video width="150" controls><source src="{}" type="video/mp4"></video>', self.file.url)
        elif self.media_type == 'Image':
            return format_html('<img src="{}" width="150" />', self.file.url)
        else:
            return 'Media type not supported in preview'
    preview.short_description = 'Preview Of Media'


class Listing(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    min_qty = models.IntegerField(default=1)
    max_qty = models.IntegerField(default=1)
    post_date = models.DateTimeField(default=timezone.now)
    update_date = models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique=True)

    class Meta:
        abstract = False
    
    def __str__(self):
        return self.name
    
    # In this code, hasattr(self, 'product') checks if the Listing instance has a related Product instance, 
    # and hasattr(self, 'service') checks for a related Service instance. 
    # You can then use this method in your ListView to display the appropriate tag.
    def get_listing_type(self):
        if hasattr(self, 'product'):
            return 'Product'
        elif hasattr(self, 'service'):
            return 'Service'
        else:
            return 'Listing'
    
    def save(self, *args, **kwargs):
        # Genereate unique slugs
        if not self.slug:
            value = self.name
            slug_candidate = slugify(value, allow_unicode=True)
            self.slug = slug_candidate
            if Listing.objects.filter(slug=self.slug).exists():
                for i in range(1, 100):
                    slug_candidate = f"{slug_candidate}-{i}"
                    if not Listing.objects.filter(slug=slug_candidate).exists():
                        self.slug = slug_candidate
                        break
        super().save(*args, **kwargs)


class Product(Listing):
    height = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    weight = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return self.name


class Service(Listing):
    available_at = models.DateTimeField(default=timezone.now)
    not_available_at = models.DateTimeField(null=True, blank=True)
    
    def __str__(self):
        return self.name


class Currency(models.Model):
    code = models.CharField(max_length=3, unique=True)
    symbol = models.CharField(max_length=3)
    name = models.CharField(max_length=200)
    
    class Meta:
        verbose_name_plural = 'Currencies'
        
    def __str__(self):
        return self.name


class Unit(models.Model):
    UNIT_TYPES = (
        ('Quantity', 'Quantity'),
        ('Weight', 'Weight'),
        ('Volume', 'Volume'),
        ('Length', 'Length'),
        ('Time', 'Time'),
        ('Area', 'Area'),
    )
    name = models.CharField(max_length=200, unique=True)
    symbol = models.CharField(max_length=10, unique=True)
    unit_type = models.CharField(max_length=8, choices=UNIT_TYPES)
    conversion_factor = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name

order_app/models.py
from django.db import models

# Create your models here.

listing/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import DetailView, ListView

from .models import * 

# Create your views here.

def index(request):
    return HttpResponse("Hello from Listing App")

class ListingListView(ListView):
    model = Listing


class ProductListView(ListView):
    model = Product
    template_name = "listing/listing_list.html"


class ServiceListView(ListView):
    model = Service
    template_name = "listing/listing_list.html"


class ListingDetailView(DetailView):
    model = Listing


class ProductDetailView(DetailView):
    model = Product
    template_name = "listing/listing_detail.html"


class ServiceDetailView(DetailView):
    model = Service
    template_name = "listing/listing_detail.html"

listing_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import DetailView, ListView

from .models import * 

# Create your views here.

def index(request):
    return HttpResponse("Hello from Listing App")

class ListingListView(ListView):
    model = Listing


class ProductListView(ListView):
    model = Product
    template_name = "listing_app/listing_list.html"


class ServiceListView(ListView):
    model = Service
    template_name = "listing_app/listing_list.html"


class ListingDetailView(DetailView):
    model = Listing


class ProductDetailView(DetailView):
    model = Product
    template_name = "listing_app/listing_detail.html"


class ServiceDetailView(DetailView):
    model = Service
    template_name = "listing_app/listing_detail.html"

order_app/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def cart(request):
    return HttpResponse("This is your cart page")

listing_app/templates/listing_app/listing_detail.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>



{% block content %}
  <div class="container mt-5">
    <div class="row">
      <div class="col-md-6">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            {% for media in object.media_set.all %}
              <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter0 }}" class="{% if forloop.first %}active{% endif %}"></li>
            {% endfor %}
          </ol>
          <div class="carousel-inner">
            {% for media in object.media_set.all %}
              <div class="carousel-item {% if forloop.first %}active{% endif %}">
                <img src="{{ media.file.url }}" class="d-block w-100" alt="{{ object.name }}">
              </div>
            {% endfor %}
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
      <div class="col-md-6">
        <h1>{{ object.name }}</h1>
        <p>{{ object.description }}</p>
        {% with object.price_set.first as price %}
          {% if price %}
            <p>
              {% if price.offerprice %}
                <del>Sale Price: {{ price.currency.symbol }}{{ price.saleprice }}</del> 
                <span class="text-success h4">Special Offer: {{ price.currency.symbol }}{{ price.offerprice }}</span>
              {% else %}
                {% if price.mrp %}
                  <del>MRP: {{ price.currency.symbol }}{{ price.mrp }}</del> 
                {% endif %}
                Sale Price: {{ price.currency.symbol }}{{ price.saleprice }}
              {% endif %}
            </p>
          {% endif %}
        {% endwith %}
        <!-- Add to cart button -->
        <a href="{% url 'add-to-cart' object.pk %}" class="btn btn-primary btn-lg btn-block">Add to Cart</a>
      </div>
    </div>
  </div>  
{% endblock %}

listing_app/templates/listing_app/listing_list.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

New Gallery of all Listings
<style>
    .card{
        transition: transform 0.2s;
    }
    .card:hover {
      transform: scale(1.01);
      box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15);
    }
</style>

{% block content %}
<div class="container">
    <div class="row">
      {% for listing in object_list %}
        <div class="col-md-4 d-flex">
          <div class="card mb-4 shadow-sm">
            {% comment %} Image carousel {% endcomment %}
            <div id="carouselExampleIndicators{{ listing.pk }}" class="carousel slide" data-ride="carousel">
              <ol class="carousel-indicators">
                  {% for media in listing.media_set.all %}
                      <li data-target="#carouselExampleIndicators{{ listing.pk }}" data-slide-to="{{ forloop.counter0 }}" class="{% if forloop.first %}active{% endif %}"></li>
                  {% endfor %}
              </ol>
              <div class="carousel-inner">
                  {% for media in listing.media_set.all %}
                      <div class="carousel-item {% if forloop.first %}active{% endif %}">
                          <img src="{{ media.file.url }}" class="d-block w-100" alt="{{ listing.name }}">
                      </div>
                  {% endfor %}
              </div>
              <a class="carousel-control-prev" href="#carouselExampleIndicators{{ listing.pk }}" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleIndicators{{ listing.pk }}" role="button" data-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
              </a>
            </div>
            {% comment %} Card body {% endcomment %}
            <div class="card-body">
              <h5 class="card-title">{{ listing.name }} 
                  <span class="badge badge-secondary">{{ listing.get_listing_type }}</span>
              </h5>
              <p class="card-text">{{ listing.description }}</p>
              {% comment %} Pricing section {% endcomment %}
              {% with listing.price_set.first as price %}
                  {% if price %}
                      <p class="card-text">
                          {% if price.offerprice %}
                              <del>Sale Price:  {{ price.currency.symbol }}{{ price.saleprice }}</del> 
                              <strong class="text-success">Special Offer:  {{ price.currency.symbol }}{{ price.offerprice }}</strong>
                          {% else %}
                            {% if price.mrp %}
                                <del>MRP: {{ price.currency.symbol }}{{ price.mrp }}</del>
                            {% endif %}
                            <strong>Sale Price:  {{ price.currency.symbol }}{{ price.saleprice }}</strong>
                          {% endif %}
                      </p>
                  {% endif %}
              {% endwith %}
              <a href="{% url listing.get_listing_type|lower|add:'-detail' listing.slug %}" class="btn btn-primary btn-lg btn-block">Grab the Deal Now!</a>
            </div>
            
          </div>
        </div>
      {% endfor %}
    </div>
</div>  
{% endblock %}